const bingoOptions = [
	{ id: 1, label: 'Pulled early', isClicked: false },
	{ id: 2, label: 'Mov. ability into death', isClicked: false },
	{ id: 3, label: 'Forgot FC actions', isClicked: false },
	{ id: 4, label: 'Ran out of pots', isClicked: false },
	{ id: 5, label: 'Uncontrollable laughing fit', isClicked: false },
	{ id: 6, label: 'Died when Swiftcast is down', isClicked: false },
	{ id: 7, label: 'Rescue to/through death', isClicked: false },
	{ id: 8, label: 'Forgot tank stance', isClicked: false },
	{ id: 9, label: 'Misplaced Tether', isClicked: false },
	{ id: 10, label: '"How did you NOT die there?"', isClicked: false },
	{ id: 11, label: '"My brother in CHRIST!"', isClicked: false },
	{ id: 12, label: 'Surprise animal', isClicked: false },
	{ id: 13, label: 'Fucked my opener (Free)', isClicked: false },
	{ id: 14, label: 'All mitigations in Shadow Realm', isClicked: false },
	{ id: 15, label: 'Server-ticked', isClicked: false },
	{ id: 16, label: 'Bad Pun', isClicked: false },
	{ id: 17, label: 'OGCD kicked from call', isClicked: false },
	{ id: 18, label: 'Baited to death', isClicked: false },
	{ id: 19, label: 'Tankbuster cleave', isClicked: false },
	{ id: 20, label: 'Hardware issue', isClicked: false },
	{ id: 21, label: 'Catgirl hate', isClicked: false },
	{ id: 22, label: 22, isClicked: false },
	{ id: 23, label: 23, isClicked: false },
	{ id: 24, label: 24, isClicked: false },
	{ id: 25, label: 25, isClicked: false },
];

export default bingoOptions;
