const memberInfo = [
	{
		name: 'Jet Laudir',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/3640299/',
		nickname: 'Psuedo FC Master',
		rank: 'FC Master',
		jobs: 'RPR, DNC',
		reasonToPlay: '',
		interests: '',
		src: '/images/members/jet_laudir.png',
		width: 1087,
		height: 1080,
		stream: 'https://www.twitch.tv/jetlaudir',
	},
	{
		name: 'Zanis Voluna',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/7189438/',
		nickname: 'Actual leader/Badass',
		rank: 'Officer',
		jobs: 'GNB, RPR, BRD, SGE',
		reasonToPlay:
			"Started playing in ARR on Eizen's recommendation because Warlords of Draenor was a disappointment. Also, Y'shtola best girl.",
		interests:
			'Tanking, all kinds of DPS. Outside of XIV, I like to play randomizers and fighting games.',
		src: '/images/members/unknown (4).png',
		width: 1920,
		height: 1080,
		stream: 'https://www.twitch.tv/zanvol',
	},
	{
		name: 'Soleil Courtois',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/16806074/',
		nickname: 'Frenchie',
		rank: 'Officer',
		jobs: 'WHM, AST, SAM',
		reasonToPlay: '',
		interests: '',
		src: '/images/members/soleil_courtois.png',
		width: 690,
		height: 972,
	},
	{
		name: 'Bardon Ambire',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/3640299/',
		nickname: 'Squawker',
		rank: 'Member',
		jobs: 'MNK, SMN',
		reasonToPlay: 'Oh my lord...',
		interests: '',
		src: '/images/members/bardon_ambire.png',
		width: 1440,
		height: 1440,
		stream: 'https://www.twitch.tv/sledgeforge',
	},
	{
		name: 'Ryohou Kamina',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/3249244/',
		nickname: '"Worst Sage in Coeurl"',
		rank: 'Member',
		jobs: 'SGE, PLD',
		reasonToPlay:
			"I've been playing XIV since 1.0, and the community and story have kept me going the entire time!",
		interests:
			'Exercise, reading, web development, and playing with my Husky to start',
		src: '/images/members/ryohou.png',
		width: 1047,
		height: 1037,
		stream: 'https://www.twitch.tv/permafun',
	},
	{
		name: 'Byron Endover',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/25852892/',
		nickname: '.........',
		rank: 'Member',
		jobs: 'SMN, GNB, SAM, DRK, WHM, SGE, BRD',
		reasonToPlay:
			"I heard about this free trial thing and a certain friend of mine was really into it, so I gave it a swing. Took me a long time for Final Fantasy to hook me in though. I actually started in Heavensward when Virus was still an ability for Summoner, but I didn't even make it to the first dungeon and put the game down for a few years. Picked it back up with Shadowbringers, and played it on and off. Once I got through the base story, I started playing it every day and haven't regretted it!",
		interests: 'Gaming, cooking, coding, corrupting the minds of the young',
		src: '/images/members/byron_endover.png',
		width: 1468,
		height: 1440,
	},
	{
		name: 'Denura Boltz',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/21557921/',
		nickname: '',
		rank: 'Member',
		jobs: 'RDM, NIN, WAR',
		reasonToPlay:
			'I started in...2018 apparently because my friends bullied me into it',
		interests: '',
		src: '/images/members/debgh2r-922ae5d8-ce3e-4898-bef3-7ce500293608.jpg',
		width: 1466,
		height: 1520,
	},
	{
		name: 'Drowning Dolphin',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/25668847/',
		nickname: '',
		rank: 'Member',
		jobs: 'BRD, DRG',
		reasonToPlay: '',
		interests: '',
		src: '/images/members/8f9QypZR_400x400.png',
		width: 265,
		height: 265,
	},
	{
		name: 'Darick Castle',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/41225687/',
		nickname: 'Bero',
		rank: 'Member',
		jobs: 'SMN',
		reasonToPlay:
			'Streamer I like did a several hour long powerpoint presentation about the game and it piqued my interest enough to try out the free trial. I bought it like the day after and some of the reason was because unlike WoW the game has functioning doors. Not kidding.',
		interests:
			'Just about anything in FFXIV, but especially maps and good storylines.',
		src: '/images/members/darick_castle.png',
		width: 1295,
		height: 1080,
	},
	{
		name: 'Bob Sylvania',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/28022077/',
		nickname: 'Bob',
		rank: 'Member',
		jobs: 'SAM',
		reasonToPlay: '',
		interests: '',
		src: '/images/members/ds6fnusepjs01.webp',
		width: 640,
		height: 1000,
	},
	{
		name: 'Annika Rinyau',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/41324168/',
		nickname: '',
		rank: 'Member',
		jobs: 'SMN',
		reasonToPlay: '',
		interests: '',
		src: '/images/members/vIh_j-8vhJk4cnAVBPu4W2lnwlHNsWJQG5BvX5ij2og.webp',
		width: 640,
		height: 886,
	},
	{
		name: 'Oo Woo',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/16569511/',
		rank: 'Member',
		jobs: 'WAR, RPR, PLD',
		reasonToPlay:
			'Legion was pretty snooze after the first patch, tried it out and had a good time until Stormblood launch. Came back for end of Shadowbringers and been having a good time with on-content.',
		interests: 'Coding, streaming, the works ya know?',
		src: '/images/members/oowoo.png',
		width: 432,
		height: 865,
		stream: 'https://www.twitch.tv/heuto',
	},
	{
		name: 'Zendinali Moulkari',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/36865763/',
		nickname: '',
		rank: 'Member',
		jobs: 'BLM',
		reasonToPlay:
			'To beat Oo Woo at this own game. #girlgaming #catgirlsrule #casterlife #WWYSHTOLAD',
		interests: '',
		src: '/images/members/229lqbgaxb021.webp',
		width: 2480,
		height: 3508,
	},
	// {
	// 	name: 'Eizen Thanatis',
	// 	link: 'https://na.finalfantasyxiv.com/lodestone/character/3450783/',
	// 	nickname: 'Lost...',
	// 	rank: 'Member',
	// 	jobs: 'SAM...',
	// 	reasonToPlay: 'Where am I?',
	// 	interests:
	// 		'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Varius quam quisque id diam vel.',
	// 	src: '/images/members/missing-person-poster-template-with-one-picture_print_big.webp',
	// 	width: 950,
	// 	height: 1260,
	// },
	// {
	// 	name: 'Kair Kair',
	// 	link: 'https://na.finalfantasyxiv.com/lodestone/character/25866310/',
	// 	nickname: 'Kairful now',
	// 	rank: 'Member',
	// 	jobs: 'SMN',
	// 	reasonToPlay: "Wait, this isn't Runescape?!?",
	// 	interests:
	// 		'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Varius quam quisque id diam vel.',
	// 	src: '/images/members/266-2662469_runescape-characters-hd-png-download.png',
	// 	width: 860,
	// 	height: 1509,
	// },
];

export default memberInfo;
