const memberInfo = [
	{
		name: 'Jet Laudir',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/3640299/',
		nickname: 'Jet Loud Deer',
		rank: 'FC Master',
		jobs: 'DNC, RPR, WHM',
		reasonToPlay:
			'I liked Final Fantasy, and really enjoyed the idea of being able to play a Final Fantasy with others',
		interests:
			"Streaming randomizers and speedrunning, being a furry, my boi G'raha Tia 😍 ",
		src: '/images/members/jet_laudir.png',
		width: 1087,
		height: 1080,
		stream: 'https://www.twitch.tv/jetlaudir',
	},
	{
		name: 'Zanis Voluna',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/7189438/',
		nickname: '"Best GNB I Know" - Oo Woo',
		rank: 'Officer',
		jobs: 'GNB, RPR, BRD, SGE',
		reasonToPlay:
			"Started playing in ARR on Eizen's recommendation because Warlords of Draenor was a disappointment. Also, Y'shtola best girl.",
		interests:
			'Tanking, all kinds of DPS. Outside of XIV, I like to play randomizers and fighting games.',
		src: '/images/members/zanis_voluna.png',
		width: 890,
		height: 1080,
		stream: 'https://www.twitch.tv/zanvol',
	},
	{
		name: 'Soleil Courtois',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/16806074/',
		nickname:
			'Frenchie, Sol, Jaequella, Angery Baby, Winner of the 2022 Most Spiteful Healer Award',
		rank: 'Officer',
		jobs: 'WHM, AST, SCH, SGE, MCH',
		reasonToPlay:
			'Oo Woo sent a meme back in 2016 and tagged me in it. I showed interest and played on and off for a few years before migrating to it as my main MMO in 2019.',
		interests:
			'Healing, Varieties of games,RP, D&D, Baking, Taking Pictures, I do art sometimes and enjoy doing character art and am currently planning out my own story. Catpeople Hater, Urianger Enjoyer',
		src: '/images/members/soleil_courtois.png',
		width: 690,
		height: 972,
		stream: 'https://www.twitch.tv/jaequella',
	},
	{
		name: 'Bardon Ambire',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/3640299/',
		nickname: 'Sledge, "Callout Dude with the memory of a Goldfish"',
		rank: 'Member',
		jobs: 'MNK, SMN, SCH, WAR, WHM',
		reasonToPlay:
			"Spent years looking for an MMO to call home, and tried out FFXIV with a couple friends back in late 2.X. After playing on-and-off for years, I fully got into FFXIV in 2019 with Shadowbringers and have been playing since. (Might've dragged Gyl'aan along with me)",
		interests:
			'High-End FFXIV Content, Glamours, Screenshots. Outside of FFXIV: Monster Hunter, JRPGs, First-Person Shooters, and a little bit of everything else',
		src: '/images/members/bardon_ambire.png',
		width: 1440,
		height: 1440,
		stream: 'https://www.twitch.tv/sledgeforge',
	},
	{
		name: 'Ryohou Kamina',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/3249244/',
		nickname: '"Worst Sage in Coeurl"',
		rank: 'Member',
		jobs: 'SAM, SGE, PLD',
		reasonToPlay:
			"I've been playing XIV since 1.0, and the community and story have kept me going the entire time!",
		interests:
			'Exercise, reading, web development, and playing with my Husky to start',
		src: '/images/members/ryouhou_kamina.png',
		width: 1249,
		height: 1563,
		stream: 'https://www.twitch.tv/permafun',
	},
	{
		name: 'Byron Endover',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/25852892/',
		nickname: '.........',
		rank: 'Member',
		jobs: 'GNB, DRK, SAM, RPR, SMN, BRD, DNC',
		reasonToPlay:
			"I heard about this free trial thing and a certain friend of mine was really into it, so I gave it a swing. Took me a long time for Final Fantasy to hook me in though. I actually started in Heavensward when Virus was still an ability for Summoner, but I didn't even make it to the first dungeon and put the game down for a few years. Picked it back up with Shadowbringers, and played it on and off. Once I got through the base story, I started playing it every day and haven't regretted it!",
		interests:
			'Gaming, cooking, coding, corrupting the minds of the young, annoying the other raid members with *opinions*',
		src: '/images/members/byron_endover.png',
		width: 1468,
		height: 1440,
	},
	// {
	// 	name: 'Denura Boltz',
	// 	link: 'https://na.finalfantasyxiv.com/lodestone/character/21557921/',
	// 	nickname: "Gyl'aan, Dragon-God of Shenanigans",
	// 	rank: 'Member',
	// 	jobs: 'RDM, NIN, SMN',
	// 	reasonToPlay:
	// 		'I started in...2018 apparently because my friends bullied me into it',
	// 	interests:
	// 		'Dragons, anime, anime with dragons, gaming, games with dragons, books, books with dragons, writing, ridiculous crossovers, writing ridiculous crossovers',
	// 	src: '/images/members/debgh2r-922ae5d8-ce3e-4898-bef3-7ce500293608.jpg',
	// 	width: 1466,
	// 	height: 1520,
	// },
	// {
	// 	name: 'Drowning Dolphin',
	// 	link: 'https://na.finalfantasyxiv.com/lodestone/character/25668847/',
	// 	nickname: 'Benchwarmer',
	// 	rank: 'Member',
	// 	jobs: 'BRD',
	// 	reasonToPlay: 'Its all Zanis' fault, been blaming him since 2017',
	// 	interests: 'Changes with the wind, at the moment I've been enjoying levelling and gardening.',
	// 	src: '/images/members/8f9QypZR_400x400.png',
	// 	width: 265,
	// 	height: 265,
	// },
	{
		name: 'Darick Castle',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/41225687/',
		nickname: 'Bero',
		rank: 'Member',
		jobs: 'SMN',
		reasonToPlay:
			'Streamer I like did a several hour long powerpoint presentation about the game and it piqued my interest enough to try out the free trial. I bought it like the day after and some of the reason was because unlike WoW the game has functioning doors. Not kidding.',
		interests:
			'Just about anything in FFXIV, but especially maps and good storylines.',
		src: '/images/members/darick_castle.png',
		width: 1295,
		height: 1080,
	},
	// {
	// 	name: 'Bob Sylvania',
	// 	link: 'https://na.finalfantasyxiv.com/lodestone/character/28022077/',
	// 	nickname: 'Bob',
	// 	rank: 'Member',
	// 	jobs: 'SAM',
	// 	reasonToPlay: '',
	// 	interests: '',
	// 	src: '/images/members/ds6fnusepjs01.webp',
	// 	width: 640,
	// 	height: 1000,
	// },
	// {
	// 	name: 'Annika Rinyau',
	// 	link: 'https://na.finalfantasyxiv.com/lodestone/character/41324168/',
	// 	nickname: '',
	// 	rank: 'Member',
	// 	jobs: 'SMN',
	// 	reasonToPlay: '',
	// 	interests: '',
	// 	src: '/images/members/vIh_j-8vhJk4cnAVBPu4W2lnwlHNsWJQG5BvX5ij2og.webp',
	// 	width: 640,
	// 	height: 886,
	// },
	{
		name: 'Oo Woo',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/16569511/',
		nickname: 'Heuto',
		rank: 'Member',
		jobs: 'PLD,WAR,WHM,BLM',
		reasonToPlay:
			'Legion was pretty snooze after the first patch, tried it out and had a good time until Stormblood launch. Came back for end of Shadowbringers and been having a good time with on-content.',
		interests:
			"Coding, streaming, the works ya know. G'raha Tia Enjoyer. Y'shtola Connisseur",
		src: '/images/members/oowoo.png',
		width: 432,
		height: 865,
		stream: 'https://www.twitch.tv/heuto',
	},
	// {
	// 	name: 'Zendinali Moulkari',
	// 	link: 'https://na.finalfantasyxiv.com/lodestone/character/36865763/',
	// 	nickname: 'Duckling, The Forever Sprout',
	// 	rank: 'Member',
	// 	jobs: 'BLM',
	// 	reasonToPlay:
	// 		'I started playing because Heuto got me into it and I really enjoy games that allow me to be very immersive with an excellent customization feature...plus I really wanted something that didn't anger me like World of Warcraft did about 98% of the time I played. Once I got through to Heavensward I was absolutely hooked and needed more...I can and will die for Ser Aymeric and Lyse.',
	// 	interests: 'Really anything to do with FFXIV, Slim Ranger, and Animal Crossing keep me sane. Writing fantasy and sci-fi themed stories and creating new OC's to forget how real life works.',
	// 	src: '/images/members/229lqbgaxb021.webp',
	// 	width: 2480,
	// 	height: 3508,
	// },
	// {
	// 	name: 'Eizen Thanatis',
	// 	link: 'https://na.finalfantasyxiv.com/lodestone/character/3450783/',
	// 	nickname: 'Lost...',
	// 	rank: 'Member',
	// 	jobs: 'SAM...',
	// 	reasonToPlay: 'Where am I?',
	// 	interests:
	// 		'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Varius quam quisque id diam vel.',
	// 	src: '/images/members/missing-person-poster-template-with-one-picture_print_big.webp',
	// 	width: 950,
	// 	height: 1260,
	// },
	// {
	// 	name: 'Kair Kair',
	// 	link: 'https://na.finalfantasyxiv.com/lodestone/character/25866310/',
	// 	nickname: 'Kairful now',
	// 	rank: 'Member',
	// 	jobs: 'SMN',
	// 	reasonToPlay: "Wait, this isn't Runescape?!?",
	// 	interests:
	// 		'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Varius quam quisque id diam vel.',
	// 	src: '/images/members/266-2662469_runescape-characters-hd-png-download.png',
	// 	width: 860,
	// 	height: 1509,
	// },
];

export default memberInfo;
