import wellKnown from 'nodemailer/lib/well-known';

const memberInfo = [
	{
		name: 'Jet Laudir',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/3640299/',
		nickname: 'Psuedo FC Master',
		rank: 'FC Master',
		jobs: 'Stripper',
		reasonToPlay: "I know I'm the leader, but...",
		interests:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Varius quam quisque id diam vel.',
		src: '/images/members/dbs8uxu-3febdb99-4532-4d3d-8dd0-2eeec3e6dda5.png',
		width: 653,
		height: 784,
		orientation: 'row',
	},
	{
		name: 'Zanis Voluna',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/7189438/',
		nickname: 'Actual leader/Badass',
		rank: 'Officer',
		jobs: 'God-tier DPS, BRD, GNB, RPR, WAR',
		reasonToPlay:
			"Started playing in ARR on Eizen's recommendation because Warlords of Draenor was a disappointment. Also, Y'shtola best girl.",
		interests:
			'Tanking, all kinds of DPS. Outside of XIV, I like to play randomizers and fighting games.',
		src: '/images/members/pmxyohf557031.webp',
		width: 1767,
		height: 2500,
	},
	{
		name: 'Soleil Courtois',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/16806074/',
		nickname: 'Frenchie',
		rank: 'Officer',
		jobs: 'WHM, AST, SAM',
		reasonToPlay: "I can't resist playing a catboi!",
		interests:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Varius quam quisque id diam vel.',
		src: '/images/members/sample-873066de9f512f102e37b0a43019ff6e.jpg',
		width: 850,
		height: 1441,
	},
	{
		name: 'Bardon Ambire',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/3640299/',
		nickname: 'Squawker',
		rank: 'Member',
		jobs: 'MNK, SMN',
		reasonToPlay: 'Oh my lord...',
		interests:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Varius quam quisque id diam vel.',
		src: '/images/members/triangle-2020-06-04T170933.webp',
		width: 2391,
		height: 2700,
	},
	{
		name: 'Ryohou Kamina',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/3249244/',
		nickname: '"Worst Sage in Coeurl"',
		rank: 'Member',
		jobs: 'SGE, PLD',
		reasonToPlay:
			"I've been playing XIV since 1.0, and the community and story have kept me going the entire time!",
		interests:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Varius quam quisque id diam vel.',
		src: '/images/members/oath_by_pizza_surgeon_d9m166u-edited.jpg',
		width: 891,
		height: 1080,
	},
	{
		name: 'Byron Endover',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/25852892/',
		nickname: '.........',
		rank: 'Member',
		jobs: 'SAM, IDIOT',
		reasonToPlay: '#horny',
		interests:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Varius quam quisque id diam vel.',
		src: '/images/members/PatrickStar_467pin.webp',
		width: 1000,
		height: 1750,
	},
	{
		name: 'Denura Boltz',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/21557921/',
		nickname: 'BEST DPS',
		rank: 'Member',
		jobs: 'Uhhh--- Casters, NIN, WAR',
		reasonToPlay:
			'I started in...2018 apparently because my friends bullied me into it',
		interests: 'Actually hang on, is this interests in XIV, or in general?',
		src: '/images/members/debgh2r-922ae5d8-ce3e-4898-bef3-7ce500293608.jpg',
		width: 1466,
		height: 1520,
	},
	{
		name: 'Drowning Dolphin',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/25668847/',
		nickname: 'Weird person playing an instrument for some reason...',
		rank: 'Member',
		jobs: 'BRD, DRG',
		reasonToPlay: 'All about the PvP',
		interests:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Varius quam quisque id diam vel.',
		src: '/images/members/8f9QypZR_400x400.png',
		width: 265,
		height: 265,
	},
	{
		name: 'Darick Castle',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/41225687/',
		nickname: 'Tons of fun',
		rank: 'Member',
		jobs: 'GNB, SCH, SMN',
		reasonToPlay: 'MEMES',
		interests:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Varius quam quisque id diam vel.',
		src: '/images/members/kadjxha3c1w21.webp',
		width: 215,
		height: 322,
	},
	{
		name: 'Bob Sylvania',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/28022077/',
		nickname: 'Bob',
		rank: 'Member',
		jobs: 'SAM...',
		reasonToPlay: 'I wanna be the best Bob I can be!',
		interests:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Varius quam quisque id diam vel.',
		src: '/images/members/ds6fnusepjs01.webp',
		width: 640,
		height: 1000,
	},
	{
		name: 'Annika Rinyau',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/41324168/',
		nickname: 'Unknown SMN Badass',
		rank: 'Member',
		jobs: 'SMN',
		reasonToPlay: "Don't know, haven't played with this person yet",
		interests:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Varius quam quisque id diam vel.',
		src: '/images/members/vIh_j-8vhJk4cnAVBPu4W2lnwlHNsWJQG5BvX5ij2og.webp',
		width: 640,
		height: 886,
	},
	{
		name: 'Oo Woo',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/16569511/',
		nickname: 'Best WAR NA',
		rank: 'Member',
		jobs: 'WAR, RPR, PLD',
		reasonToPlay: '',
		interests:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Varius quam quisque id diam vel.',
		src: '/images/members/Dd5gh7yV4AAJlLu.jpg',
		width: 1200,
		height: 1200,
	},
	{
		name: 'Zendinali Moulkari',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/36865763/',
		nickname: 'Cute magick catgirl, PEW PEW!',
		rank: 'Member',
		jobs: 'BLM, maybe a little SAM',
		reasonToPlay:
			'To beat Oo Woo at this own game. #girlgaming #catgirlsrule #casterlife #WWYSHTOLAD',
		interests:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Varius quam quisque id diam vel.',
		src: '/images/members/229lqbgaxb021.webp',
		width: 2480,
		height: 3508,
	},
	{
		name: 'Eizen Thanatis',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/3450783/',
		nickname: 'Lost...',
		rank: 'Member',
		jobs: 'SAM...',
		reasonToPlay: 'Where am I?',
		interests:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Varius quam quisque id diam vel.',
		src: '/images/members/missing-person-poster-template-with-one-picture_print_big.webp',
		width: 950,
		height: 1260,
	},
	{
		name: 'Kair Kair',
		link: 'https://na.finalfantasyxiv.com/lodestone/character/25866310/',
		nickname: 'Kairful now',
		rank: 'Member',
		jobs: 'SMN',
		reasonToPlay: "Wait, this isn't Runescape?!?",
		interests:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Varius quam quisque id diam vel.',
		src: '/images/members/266-2662469_runescape-characters-hd-png-download.png',
		width: 860,
		height: 1509,
	},
];

export default memberInfo;
